// action types
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const DESELECT_CUSTOMER = 'DESELECT_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const EDIT_CUSTOMER_INPUT_CHANGE = 'EDIT_CUSTOMER_INPUT_CHANGE';
export const NEW_CUSTOMER_INPUT_CHANGE = 'NEW_CUSTOMER_INPUT_CHANGE';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';

// other constants
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const GET_CUSTOMER_DATA_RECEIVED = 'GET_CUSTOMER_DATA_RECEIVED';
export const SEARCH_CUSTOMER_DATA = 'SEARCH_CUSTOMER_DATA';

export const CREATE_MOWER = 'CREATE_MOWER';
export const DESELECT_MOWER = 'DESELECT_MOWER';
export const EDIT_MOWER = 'EDIT_MOWER';
export const EDIT_MOWER_INPUT_CHANGE = 'EDIT_MOWER_INPUT_CHANGE';
export const NEW_MOWER_INPUT_CHANGE = 'NEW_MOWER_INPUT_CHANGE';
export const SELECT_MOWER = 'SELECT_MOWER';
export const UPDATE_MOWER = 'UPDATE_MOWER';
export const UPDATE_MOWER_ERROR = 'UPDATE_MOWER_ERROR';
export const UPDATE_MOWER_SUCCESS = 'UPDATE_MOWER_SUCCESS';

// other constants
export const CREATE_MOWER_ERROR = 'CREATE_MOWER_ERROR';
export const CREATE_MOWER_SUCCESS = 'CREATE_MOWER_SUCCESS';
export const GET_MOWER_DATA = 'GET_MOWER_DATA';
export const GET_MOWER_DATA_RECEIVED = 'GET_MOWER_DATA_RECEIVED';
export const GET_MOWERS_RECEIVED = 'GET_MOWERS_RECEIVED';
export const SEARCH_MOWER_DATA = 'SEARCH_MOWER_DATA';
