// action types
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const DESELECT_CUSTOMER = 'DESELECT_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const EDIT_USER_INPUT_CHANGE = 'EDIT_USER_INPUT_CHANGE';
export const NEW_USER_INPUT_CHANGE = 'NEW_USER_INPUT_CHANGE';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';

// other constants
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const GET_CUSTOMER_DATA_RECEIVED = 'GET_CUSTOMER_DATA_RECEIVED';
export const SEARCH_CUSTOMER_DATA = 'SEARCH_CUSTOMER_DATA';
